"""Pinned AWS AI-DLC source graph.

The source graph is definition-only. It records the user-confirmed upstream
methodology and its DAG/scope structure without replacing the provisional
Agora method or granting routing/dispatch authority.
"""
from __future__ import annotations

from agora.protocol.hashing import seal_model_payload
from agora.protocol.methodology import MethodologySourceGraph

_SOURCE_ARTIFACTS = (
    (
        "specification",
        "assets/AI-DLC-Workflows-2.0-Specification.pdf",
        "b16fabba759a058825ba4517dcffaadcbc21d2d42b8c3af140dbc9dcbd59242a",
    ),
    (
        "stage_definition",
        "core/aidlc-common/protocols/stage-definition.md",
        "9306991ece75439cd53677f771f9295140ebde9f5709023beb0f8026bfc5a4c4",
    ),
    (
        "rework_protocol",
        "core/aidlc-common/protocols/stage-protocol-recovery.md",
        "c0931e3e0dd76b9dcc915aaa12a96a4017128e62c156ac9eac43244f9d9005b2",
    ),
    (
        "compiled_graph",
        "dist/codex/.codex/tools/data/stage-graph.json",
        "9de074e882c18bcc1285a953366a7793149d05a349657a7989f0e54b2fdd1430",
    ),
    (
        "scope_grid",
        "dist/codex/.codex/tools/data/scope-grid.json",
        "acd58b104b16dc8f024ea7c96de57efb94687be5e2583cef207beb93fc524d54",
    ),
    (
        "stage",
        "core/aidlc-common/stages/initialization/workspace-scaffold.md",
        "9fcbc58a399452bd46d2ef63c355d7d968a0f51055afcf791d9d4823e452b4e0",
    ),
    (
        "stage",
        "core/aidlc-common/stages/initialization/workspace-detection.md",
        "a7b72b7878b2b66e112e9f3f3cb5dcbb39024f3301a1da91741e52dff2ab7a98",
    ),
    (
        "stage",
        "core/aidlc-common/stages/initialization/state-init.md",
        "efcff5545b3027d2be3c80820b0334195a04e3f14ef8d16f0031f542eaf10607",
    ),
    (
        "stage",
        "core/aidlc-common/stages/ideation/intent-capture.md",
        "18d0673ceb35de4cdebb466e6eb130cdddf009af751e0118decc51ba1fa53a26",
    ),
    (
        "stage",
        "core/aidlc-common/stages/ideation/market-research.md",
        "6bc19cb4c78acf49fc5b65d188acfd5ef1b18ba587d9fe05f1bfcf88f9243353",
    ),
    (
        "stage",
        "core/aidlc-common/stages/ideation/feasibility.md",
        "264750d5b5b73efe8ec972b071680c801d25d0c4c5bde01a12cfb6b795268c53",
    ),
    (
        "stage",
        "core/aidlc-common/stages/ideation/scope-definition.md",
        "3715f30c01027b0eb201307c745b8441d06047fb28b9f77dd72d311d60e52487",
    ),
    (
        "stage",
        "core/aidlc-common/stages/ideation/team-formation.md",
        "daa1201738e517b51afbb9e07bc06e5be0645e93b39cdb2d16794e549a39ba1c",
    ),
    (
        "stage",
        "core/aidlc-common/stages/ideation/rough-mockups.md",
        "4bd68239e914fd49995df66a22e0ef80b1165c56381255698f6a4b86157742c2",
    ),
    (
        "stage",
        "core/aidlc-common/stages/ideation/approval-handoff.md",
        "97ba3380535a04866fae1e1584b8e03c9bca27ab0eb61d41c779ec94d9200ea2",
    ),
    (
        "stage",
        "core/aidlc-common/stages/inception/reverse-engineering.md",
        "56bb63fd8bb70565acfe04d36bd16c277463ee17b5b84b76f9fc801797ec545f",
    ),
    (
        "stage",
        "core/aidlc-common/stages/inception/practices-discovery.md",
        "a399923c47f6d08f557add896bb8fd7f512ae55a2f270a32b8dcbb78ee4e23ad",
    ),
    (
        "stage",
        "core/aidlc-common/stages/inception/requirements-analysis.md",
        "97d33c0d3e0f018e71d61cc72f5161e79cc6cb1c081a0916d8496c5846a9c5d0",
    ),
    (
        "stage",
        "core/aidlc-common/stages/inception/user-stories.md",
        "2ce3cb8dc8ea196305fdef6b9b4c4138995952dc9f3bf41754d849dce8a3e762",
    ),
    (
        "stage",
        "core/aidlc-common/stages/inception/refined-mockups.md",
        "4fb3b5eb2e3ca17026cbcc439be383c8ef09338dd7a2516907b8656716019908",
    ),
    (
        "stage",
        "core/aidlc-common/stages/inception/application-design.md",
        "c93379aa006be227275d09e1d8200ed37d72baff81ede78aba62411c3918604e",
    ),
    (
        "stage",
        "core/aidlc-common/stages/inception/units-generation.md",
        "dfa5a7cd8e5a96d949c0bd806d893a06cd9318b757a55859f8501573fd6e2d40",
    ),
    (
        "stage",
        "core/aidlc-common/stages/inception/delivery-planning.md",
        "c7739248f343c06a0509a5c553fcf9455ffc42ddeeb3bad492a0261434bcd057",
    ),
    (
        "stage",
        "core/aidlc-common/stages/construction/functional-design.md",
        "936eac95d9b96a88ace7f4a7190a3738cddcd32e760740cd0369b23d40617f60",
    ),
    (
        "stage",
        "core/aidlc-common/stages/construction/nfr-requirements.md",
        "e608517267fb90c625287ad5d83ad48ad4bf05b97031a91672d61993092c5e8b",
    ),
    (
        "stage",
        "core/aidlc-common/stages/construction/nfr-design.md",
        "06f44a3a5b3a171fb273064354f268d3e48e61dcff849c0e3229fd80bdc04b3a",
    ),
    (
        "stage",
        "core/aidlc-common/stages/construction/infrastructure-design.md",
        "69d3b3c0b19e5dc6e3fcb8e4ee692f25b99ccb65eb7b4109f15e271252060e85",
    ),
    (
        "stage",
        "core/aidlc-common/stages/construction/code-generation.md",
        "165073c2ca1b826a43927bc2ad258dbaad63995848454647634a1851c391ea67",
    ),
    (
        "stage",
        "core/aidlc-common/stages/construction/build-and-test.md",
        "a9fd0aacdd80db4e8633a23a00c25e9f5d460b2b4434674ae5b9112c682e3741",
    ),
    (
        "stage",
        "core/aidlc-common/stages/construction/ci-pipeline.md",
        "c01abfc21776af808e91fba79f40778789f32376b1bd842f52b8d855fa02ad8d",
    ),
    (
        "stage",
        "core/aidlc-common/stages/operation/deployment-pipeline.md",
        "a4de65fa57411c72ed8b3e29743ea0dd11c22680effbe61103cdb711ad4a0c0b",
    ),
    (
        "stage",
        "core/aidlc-common/stages/operation/environment-provisioning.md",
        "edd8d520dc1b9c0f0b034e3adf38b80793898338c7f2d64800af2acb92b7cb2a",
    ),
    (
        "stage",
        "core/aidlc-common/stages/operation/deployment-execution.md",
        "20c409d663903e9ca9ef529275f3b026007d1affded9d04aeb655cd284ea3e79",
    ),
    (
        "stage",
        "core/aidlc-common/stages/operation/observability-setup.md",
        "515523a5ce297a58b34a50ddd9c87e9eaa20f53bd5049491d9776ef323ea8207",
    ),
    (
        "stage",
        "core/aidlc-common/stages/operation/incident-response.md",
        "756068a641bfbf612179fb913714e8e3f34b6bc09c627c113ff8d290681d90cb",
    ),
    (
        "stage",
        "core/aidlc-common/stages/operation/performance-validation.md",
        "081830b96289e230af5768ec1dbadce8e702b27be38ec5bf47db0530c55be65d",
    ),
    (
        "stage",
        "core/aidlc-common/stages/operation/feedback-optimization.md",
        "ac8ca1c41168bbc7fe1b383052f186d0a774522845c870d3186796b392015585",
    ),
    (
        "scope",
        "core/scopes/aidlc-bugfix.md",
        "d393cce690a8780c95b0173b85ae86dae54f6c17201529abd196b22ab603f18d",
    ),
    (
        "scope",
        "core/scopes/aidlc-enterprise.md",
        "1a9adecb8b4b3473e76fe7e782a02b3952555f997f24a892eb7e7f79097dac8e",
    ),
    (
        "scope",
        "core/scopes/aidlc-feature.md",
        "dfdb2606f068615f1f1aa6604944ded6923ff9464c6330795b245110ab23be4e",
    ),
    (
        "scope",
        "core/scopes/aidlc-infra.md",
        "7699bc2ea5ed2d1c13a4e8e638d6e2f8d932f4b9635e2df6f7ee2e8f465b9d8f",
    ),
    (
        "scope",
        "core/scopes/aidlc-mvp.md",
        "c2b74fb3cf3483e9b58291d49fca3f4b954dcd93de83f55cf5f5e49607405f55",
    ),
    (
        "scope",
        "core/scopes/aidlc-poc.md",
        "6f317f26503068122a6b036af24ef59e2f2c2c4088d34a9e5f3b87410cb04cc8",
    ),
    (
        "scope",
        "core/scopes/aidlc-refactor.md",
        "2214a9090e8ca0cdc77a546bc834e489a7bcb4953da5d19add46b91cf88a103a",
    ),
    (
        "scope",
        "core/scopes/aidlc-security-patch.md",
        "5cd50e52cc31b60ea9fe810acb3f4dd0d33523d63cb8eaea2c59d4f3244cd2ba",
    ),
    (
        "scope",
        "core/scopes/aidlc-workshop.md",
        "6d499edff201ded4199cc5ab472d6a143af0cbfc463c3e4bae4d5877dd71015c",
    ),
)

_ALL_SCOPES = (
    "enterprise",
    "feature",
    "mvp",
    "poc",
    "bugfix",
    "refactor",
    "infra",
    "security-patch",
    "workshop",
)

_STAGE_ROWS = (
    (
        "0.1",
        "workspace-scaffold",
        "Workspace Scaffold",
        "initialization",
        "always",
        "inline",
        None,
        (),
        _ALL_SCOPES,
        "core/aidlc-common/stages/initialization/workspace-scaffold.md",
    ),
    (
        "0.2",
        "workspace-detection",
        "Workspace Detection",
        "initialization",
        "always",
        "inline",
        None,
        ("workspace-scaffold",),
        _ALL_SCOPES,
        "core/aidlc-common/stages/initialization/workspace-detection.md",
    ),
    (
        "0.3",
        "state-init",
        "State Initialization",
        "initialization",
        "always",
        "inline",
        None,
        ("workspace-detection",),
        _ALL_SCOPES,
        "core/aidlc-common/stages/initialization/state-init.md",
    ),
    (
        "1.1",
        "intent-capture",
        "Intent Capture & Framing",
        "ideation",
        "always",
        "inline",
        None,
        (),
        ("enterprise", "feature", "mvp", "poc"),
        "core/aidlc-common/stages/ideation/intent-capture.md",
    ),
    (
        "1.2",
        "market-research",
        "Market Research",
        "ideation",
        "conditional",
        "inline",
        None,
        ("intent-capture",),
        ("enterprise", "feature"),
        "core/aidlc-common/stages/ideation/market-research.md",
    ),
    (
        "1.3",
        "feasibility",
        "Feasibility & Constraints",
        "ideation",
        "conditional",
        "inline",
        None,
        ("intent-capture", "market-research"),
        ("enterprise", "feature", "mvp"),
        "core/aidlc-common/stages/ideation/feasibility.md",
    ),
    (
        "1.4",
        "scope-definition",
        "Scope Definition",
        "ideation",
        "always",
        "inline",
        None,
        ("intent-capture", "feasibility"),
        ("enterprise", "feature", "mvp"),
        "core/aidlc-common/stages/ideation/scope-definition.md",
    ),
    (
        "1.5",
        "team-formation",
        "Team Formation",
        "ideation",
        "conditional",
        "inline",
        None,
        ("scope-definition",),
        ("enterprise", "feature"),
        "core/aidlc-common/stages/ideation/team-formation.md",
    ),
    (
        "1.6",
        "rough-mockups",
        "Rough Mockups",
        "ideation",
        "conditional",
        "inline",
        None,
        ("scope-definition", "team-formation"),
        ("enterprise", "feature", "mvp"),
        "core/aidlc-common/stages/ideation/rough-mockups.md",
    ),
    (
        "1.7",
        "approval-handoff",
        "Approval & Handoff",
        "ideation",
        "always",
        "inline",
        None,
        (
            "intent-capture",
            "feasibility",
            "scope-definition",
            "team-formation",
            "rough-mockups",
        ),
        ("enterprise", "feature"),
        "core/aidlc-common/stages/ideation/approval-handoff.md",
    ),
    (
        "2.1",
        "reverse-engineering",
        "Reverse Engineering",
        "inception",
        "conditional",
        "subagent",
        None,
        ("state-init",),
        (
            "enterprise",
            "feature",
            "mvp",
            "poc",
            "bugfix",
            "refactor",
            "security-patch",
            "workshop",
        ),
        "core/aidlc-common/stages/inception/reverse-engineering.md",
    ),
    (
        "2.2",
        "practices-discovery",
        "Practices Discovery",
        "inception",
        "conditional",
        "inline",
        None,
        ("state-init", "reverse-engineering"),
        ("enterprise", "feature", "mvp", "infra", "workshop"),
        "core/aidlc-common/stages/inception/practices-discovery.md",
    ),
    (
        "2.3",
        "requirements-analysis",
        "Requirements Analysis",
        "inception",
        "always",
        "inline",
        None,
        ("approval-handoff", "reverse-engineering"),
        _ALL_SCOPES,
        "core/aidlc-common/stages/inception/requirements-analysis.md",
    ),
    (
        "2.4",
        "user-stories",
        "User Stories",
        "inception",
        "conditional",
        "inline",
        None,
        ("requirements-analysis",),
        ("enterprise", "feature", "mvp", "workshop"),
        "core/aidlc-common/stages/inception/user-stories.md",
    ),
    (
        "2.5",
        "refined-mockups",
        "Refined Mockups",
        "inception",
        "conditional",
        "inline",
        None,
        ("user-stories",),
        ("enterprise", "feature", "mvp", "workshop"),
        "core/aidlc-common/stages/inception/refined-mockups.md",
    ),
    (
        "2.6",
        "application-design",
        "Application Design",
        "inception",
        "conditional",
        "inline",
        None,
        ("requirements-analysis", "refined-mockups"),
        ("enterprise", "feature", "mvp", "workshop"),
        "core/aidlc-common/stages/inception/application-design.md",
    ),
    (
        "2.7",
        "units-generation",
        "Units Generation",
        "inception",
        "always",
        "inline",
        None,
        ("application-design",),
        ("enterprise", "feature", "mvp", "workshop"),
        "core/aidlc-common/stages/inception/units-generation.md",
    ),
    (
        "2.8",
        "delivery-planning",
        "Delivery Planning",
        "inception",
        "always",
        "inline",
        None,
        ("units-generation",),
        ("enterprise", "feature", "mvp", "workshop"),
        "core/aidlc-common/stages/inception/delivery-planning.md",
    ),
    (
        "3.1",
        "functional-design",
        "Functional Design",
        "construction",
        "conditional",
        "inline",
        "unit-of-work",
        ("units-generation",),
        ("enterprise", "feature", "mvp", "refactor", "workshop"),
        "core/aidlc-common/stages/construction/functional-design.md",
    ),
    (
        "3.2",
        "nfr-requirements",
        "NFR Requirements",
        "construction",
        "conditional",
        "inline",
        "unit-of-work",
        ("units-generation", "functional-design"),
        ("enterprise", "feature", "mvp", "infra", "security-patch", "workshop"),
        "core/aidlc-common/stages/construction/nfr-requirements.md",
    ),
    (
        "3.3",
        "nfr-design",
        "NFR Design",
        "construction",
        "conditional",
        "inline",
        "unit-of-work",
        ("units-generation", "nfr-requirements"),
        ("enterprise", "feature", "mvp", "infra", "workshop"),
        "core/aidlc-common/stages/construction/nfr-design.md",
    ),
    (
        "3.4",
        "infrastructure-design",
        "Infrastructure Design",
        "construction",
        "conditional",
        "inline",
        "unit-of-work",
        ("units-generation", "nfr-design"),
        ("enterprise", "feature", "mvp", "infra", "workshop"),
        "core/aidlc-common/stages/construction/infrastructure-design.md",
    ),
    (
        "3.5",
        "code-generation",
        "Code Generation",
        "construction",
        "always",
        "subagent",
        "unit-of-work",
        (
            "units-generation",
            "functional-design",
            "nfr-requirements",
            "nfr-design",
            "infrastructure-design",
        ),
        (
            "enterprise",
            "feature",
            "mvp",
            "poc",
            "bugfix",
            "refactor",
            "security-patch",
            "workshop",
        ),
        "core/aidlc-common/stages/construction/code-generation.md",
    ),
    (
        "3.6",
        "build-and-test",
        "Build and Test",
        "construction",
        "always",
        "inline",
        None,
        ("code-generation",),
        (
            "enterprise",
            "feature",
            "mvp",
            "poc",
            "bugfix",
            "refactor",
            "security-patch",
            "workshop",
        ),
        "core/aidlc-common/stages/construction/build-and-test.md",
    ),
    (
        "3.7",
        "ci-pipeline",
        "CI Pipeline",
        "construction",
        "conditional",
        "inline",
        None,
        ("build-and-test",),
        ("enterprise", "feature", "mvp", "infra", "workshop"),
        "core/aidlc-common/stages/construction/ci-pipeline.md",
    ),
    (
        "4.1",
        "deployment-pipeline",
        "Deployment Pipeline",
        "operation",
        "conditional",
        "inline",
        None,
        ("ci-pipeline", "infrastructure-design"),
        ("enterprise", "feature", "infra", "security-patch", "workshop"),
        "core/aidlc-common/stages/operation/deployment-pipeline.md",
    ),
    (
        "4.2",
        "environment-provisioning",
        "Environment Provisioning",
        "operation",
        "conditional",
        "inline",
        None,
        ("infrastructure-design", "deployment-pipeline"),
        ("enterprise", "feature", "infra", "workshop"),
        "core/aidlc-common/stages/operation/environment-provisioning.md",
    ),
    (
        "4.3",
        "deployment-execution",
        "Deployment Execution",
        "operation",
        "conditional",
        "inline",
        None,
        ("deployment-pipeline", "environment-provisioning"),
        ("enterprise", "feature", "infra", "security-patch", "workshop"),
        "core/aidlc-common/stages/operation/deployment-execution.md",
    ),
    (
        "4.4",
        "observability-setup",
        "Observability Setup",
        "operation",
        "conditional",
        "inline",
        None,
        ("nfr-design", "infrastructure-design", "deployment-execution"),
        ("enterprise", "feature", "infra", "workshop"),
        "core/aidlc-common/stages/operation/observability-setup.md",
    ),
    (
        "4.5",
        "incident-response",
        "Incident Response",
        "operation",
        "conditional",
        "inline",
        None,
        ("observability-setup",),
        ("enterprise", "feature", "workshop"),
        "core/aidlc-common/stages/operation/incident-response.md",
    ),
    (
        "4.6",
        "performance-validation",
        "Performance Validation",
        "operation",
        "conditional",
        "inline",
        None,
        ("nfr-requirements", "nfr-design", "observability-setup"),
        ("enterprise", "feature", "workshop"),
        "core/aidlc-common/stages/operation/performance-validation.md",
    ),
    (
        "4.7",
        "feedback-optimization",
        "Feedback & Optimization",
        "operation",
        "conditional",
        "inline",
        None,
        (
            "observability-setup",
            "deployment-execution",
            "incident-response",
            "performance-validation",
        ),
        ("enterprise", "feature", "workshop"),
        "core/aidlc-common/stages/operation/feedback-optimization.md",
    ),
)

_SCOPE_ROWS = (
    ("bugfix", "minimal", None, "core/scopes/aidlc-bugfix.md"),
    ("enterprise", "comprehensive", None, "core/scopes/aidlc-enterprise.md"),
    ("feature", "standard", None, "core/scopes/aidlc-feature.md"),
    ("infra", "standard", None, "core/scopes/aidlc-infra.md"),
    ("mvp", "standard", None, "core/scopes/aidlc-mvp.md"),
    ("poc", "minimal", None, "core/scopes/aidlc-poc.md"),
    ("refactor", "minimal", None, "core/scopes/aidlc-refactor.md"),
    (
        "security-patch",
        "minimal",
        None,
        "core/scopes/aidlc-security-patch.md",
    ),
    ("workshop", "standard", "minimal", "core/scopes/aidlc-workshop.md"),
)


def build_aws_aidlc_v2_3_source_graph() -> MethodologySourceGraph:
    payload = {
        "schema_version": "1.0",
        "methodology_id": "aws-aidlc-workflows",
        "methodology_version": "2.3.0",
        "authority_basis": "user_confirmed_official_source",
        "provisional": False,
        "source": {
            "repository_url": "https://github.com/awslabs/aidlc-workflows",
            "release_tag": "v2.3.0",
            "commit_sha": "29a31f7899731b53f2b8d7f76cd223f9a8a25859",
            "license_spdx": "Apache-2.0",
            "artifacts": [
                {"role": role, "path": path, "content_sha256": content_sha256}
                for role, path, content_sha256 in _SOURCE_ARTIFACTS
            ],
            "external_artifacts": [
                {
                    "role": "method_definition",
                    "url": (
                        "https://prod.d13rzhkk8cj2z0.amplifyapp.com/aidlc.pdf"
                    ),
                    "content_sha256": (
                        "6fdd881f6a56a4d1bed3605ca9c167011f92ef6430588679311430ce95fc692f"
                    ),
                }
            ],
        },
        "phases": [
            "initialization",
            "ideation",
            "inception",
            "construction",
            "operation",
        ],
        "stages": [
            {
                "source_number": source_number,
                "stage_key": stage_key,
                "title": title,
                "phase": phase,
                "execution": execution,
                "mode": mode,
                "for_each_artifact": for_each_artifact,
                "requires_stage": list(requires_stage),
                "scopes": list(scopes),
                "source_path": source_path,
            }
            for (
                source_number,
                stage_key,
                title,
                phase,
                execution,
                mode,
                for_each_artifact,
                requires_stage,
                scopes,
                source_path,
            ) in _STAGE_ROWS
        ],
        "scopes": [
            {
                "scope_key": scope_key,
                "depth": depth,
                "test_strategy": test_strategy,
                "source_path": source_path,
            }
            for scope_key, depth, test_strategy, source_path in _SCOPE_ROWS
        ],
        "structured_rework_edges": False,
        "routing_authority": False,
        "dispatch_authority": False,
        "unresolved_execution_requirements": [
            "stage-contract-materialization",
            "agora-runtime-role-mapping",
            "gate-requirement-mapping",
            "budget-policy-mapping",
            "bounded-rework-limits",
            "methodology-activation-migration",
        ],
    }
    return MethodologySourceGraph.model_validate(
        seal_model_payload(MethodologySourceGraph, payload)
    )


AWS_AIDLC_V2_3_SOURCE_GRAPH = build_aws_aidlc_v2_3_source_graph()

__all__ = [
    "AWS_AIDLC_V2_3_SOURCE_GRAPH",
    "build_aws_aidlc_v2_3_source_graph",
]
